controller_list:
  - name: fake_arm_controller
    joints:
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
  - name: fake_gripper_controller
    joints:
      - arm5r_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: release